# Generated by Django 5.2.17 on 2026-09-11 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger', models.CharField(blank=True, default='', help_text='Why the review was raised.', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=12)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Admin capabilities at the time of review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(blank=True, choices=[('KEEP', 'Keep access'), ('MODIFY', 'Modify access'), ('REVOKE', 'Revoke access')], default='', max_length=8)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_reviews_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADMIN_ROLE_CHANGE', "Change an administrator's role"), ('ROLE_CAPABILITY_CHANGE', 'Change capabilities of an administrative role'), ('PRIVILEGED_ACCOUNT_DEACTIVATE', 'Deactivate a privileged account')], max_length=40)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Parameters needed to execute the change.')),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved & executed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by requester'), ('FAILED', 'Approved but execution failed')], db_index=True, default='PENDING', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
