# Generated by Django 5.0.14 on 2026-09-10 11:49

import accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('weight', models.PositiveSmallIntegerField(help_text='Ordering value; higher weight = more sensitive.', unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_classified', models.BooleanField(default=False, help_text='Whether this level belongs to the classified band.')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('officer_id', models.CharField(help_text='Unique officer identifier (e.g. OFF-052).', max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('account_status', models.CharField(choices=[('PENDING', 'Pending'), ('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked'), ('DISABLED', 'Disabled'), ('DEACTIVATED', 'Deactivated')], default='PENDING', max_length=16)),
                ('rank', models.CharField(blank=True, default='', max_length=64)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('secret_code_configured', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('clearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.clearancelevel')),
            ],
            options={
                'verbose_name': 'officer',
                'verbose_name_plural': 'officers',
                'ordering': ['officer_id'],
            },
            managers=[
                ('objects', accounts.managers.OfficerManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('SECRET_CODE', 'Secret code'), ('TOTP', 'TOTP authenticator'), ('HARDWARE_TOKEN', 'Hardware token')], max_length=16)),
                ('secret_hash', models.CharField(help_text='Salted HMAC digest of the factor secret. Never plaintext.', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('NATIONAL', 'National'), ('STATE', 'State'), ('DISTRICT', 'District')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent level (State → District → ...).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'organizations',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('HQ', 'Headquarters'), ('INVESTIGATION', 'Investigation Unit'), ('CYBER', 'Cyber Unit'), ('FORENSIC', 'Forensic Unit'), ('ADMINISTRATION', 'Administration Unit')], default='HQ', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='The district/state/national organization this unit belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent unit for nested units.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.organizationunit')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='officer',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.organizationunit'),
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('classified', 'Classified'), ('it_admin', 'IT / Admin'), ('general', 'General')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_restricted', models.BooleanField(default=False, help_text='Restricted portals require additional clearance checks.')),
                ('min_clearance', models.ForeignKey(blank=True, help_text='If set, entry requires at least this clearance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.clearancelevel')),
            ],
        ),
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to=settings.AUTH_USER_MODEL)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='accounts.portal')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rank_weight', models.PositiveSmallIntegerField(default=0, help_text='Display ordering only. Carries NO authorization weight.')),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_portals', models.ManyToManyField(blank=True, related_name='roles', to='accounts.portal')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission')),
            ],
            options={
                'ordering': ['rank_weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='officer',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.role'),
        ),
        migrations.AddConstraint(
            model_name='authenticationfactor',
            constraint=models.UniqueConstraint(fields=('officer', 'factor_type'), name='uniq_officer_factor_type'),
        ),
        migrations.AddConstraint(
            model_name='organizationunit',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_unit_org_name'),
        ),
        migrations.AddConstraint(
            model_name='portalaccess',
            constraint=models.UniqueConstraint(fields=('officer', 'portal'), name='uniq_officer_portal'),
        ),
        migrations.AddConstraint(
            model_name='officer',
            constraint=models.CheckConstraint(check=models.Q(('officer_id__regex', '^[A-Z0-9][A-Z0-9\\-]*$')), name='officer_id_uppercase'),
        ),
    ]
