# Generated by Django 5.2.17 on 2026-09-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_operational_case_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='kind',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('INVESTIGATION', 'Investigation Unit'), ('CYBER', 'Cyber Unit'), ('FORENSIC', 'Forensic Unit'), ('ADMINISTRATION', 'Administration Unit'), ('POLICE_STATION', 'Police Station')], default='HQ', max_length=24),
        ),
    ]
