# Generated by Django 5.1.7 on 2026-09-13 18:22

import django.db.models.deletion
import general.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('case_type', models.CharField(max_length=80)),
                ('police_station', models.CharField(blank=True, max_length=150)),
                ('investigating_agency', models.CharField(blank=True, max_length=150)),
                ('incident_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('complainant_name', models.CharField(blank=True, max_length=160)),
                ('complainant_contact', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fir_document', models.FileField(blank=True, null=True, upload_to=general.models.case_storage_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=general.models.case_storage_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='general.caserecord')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
