# Generated by Django 5.2.17 on 2026-09-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_identity_registries'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='Sensitivity of this case; access requires at least this clearance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.clearancelevel'),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Jurisdiction (district / state) the case belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Case owner (full control)'), ('INVESTIGATOR', 'Investigating officer'), ('SUPERVISOR', 'Supervising officer (read-only oversight)'), ('VIEWER', 'Viewer (read-only)')], default='INVESTIGATOR', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='general.caserecord')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['officer', 'revoked_at'], name='general_cas_officer_3b0746_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('case', 'officer'), name='uniq_active_case_assignment')],
            },
        ),
    ]
