# Generated by Django 5.2.17 on 2026-09-15 22:07

import django.db.models.deletion
import general.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organizationunit_kind'),
        ('general', '0002_caserecord_classification_caserecord_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevidencefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Station / unit that owns this case (hierarchical access root).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.organizationunit'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Case owner (full control)'), ('INVESTIGATOR', 'Investigating officer'), ('SUPERVISOR', 'Supervising officer (oversight)'), ('VIEWER', 'Viewer (read-only)')], default='INVESTIGATOR', max_length=16),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('CASE', 'This case'), ('SELECTED', 'Selected cases'), ('STATION', 'Station / unit'), ('JURISDICTION', 'Jurisdiction')], default='CASE', max_length=16)),
                ('resource_type', models.CharField(choices=[('case', 'Case'), ('document', 'Document'), ('fir', 'FIR'), ('evidence', 'Evidence')], default='case', max_length=16)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actions', models.JSONField(default=list, help_text='Actions this grant confers.')),
                ('reason', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=12)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants_approved', to=settings.AUTH_USER_MODEL)),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants_made', to=settings.AUTH_USER_MODEL)),
                ('recipient_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.department')),
                ('recipient_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
                ('recipient_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.organization')),
                ('recipient_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.organizationunit')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('case', 'Case'), ('document', 'Document'), ('fir', 'FIR'), ('evidence', 'Evidence')], default='case', max_length=16)),
                ('resource_id', models.CharField(max_length=64)),
                ('actions', models.JSONField(default=list)),
                ('reason', models.CharField(max_length=255)),
                ('duration_days', models.PositiveSmallIntegerField(default=7)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='general.accessgrant')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=general.models.case_storage_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='general.caserecord')),
                ('classification', models.ForeignKey(blank=True, help_text='Defaults to the case classification when left empty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.clearancelevel')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='general.caserecord')),
                ('from_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organizationunit')),
                ('to_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organizationunit')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['resource_type', 'resource_id', 'status'], name='general_acc_resourc_076104_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['recipient_officer', 'status'], name='general_acc_recipie_aa4cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['status', 'expires_at'], name='general_acc_status_5d60ab_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['resource_type', 'resource_id', 'status'], name='general_acc_resourc_beba4f_idx'),
        ),
    ]
