# Generated by Django 5.0.14 on 2026-09-10 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('officer_id_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('portal', models.CharField(blank=True, default='', max_length=16)),
                ('resource_type', models.CharField(blank=True, default='', max_length=48)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(blank=True, default='', max_length=48)),
                ('result', models.CharField(blank=True, default='', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('session_id', models.CharField(blank=True, default='', help_text='SHA-256 of the session key (not the raw cookie).', max_length=64)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_events', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', '-occurred_at'], name='audit_audit_event_t_adc3c6_idx'), models.Index(fields=['officer', '-occurred_at'], name='audit_audit_officer_e3c6a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ALERT', 'Alert'), ('CRITICAL', 'Critical')], default='INFO', max_length=12)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', '-occurred_at'], name='audit_secur_event_t_9a2957_idx'), models.Index(fields=['severity', '-occurred_at'], name='audit_secur_severit_afe91b_idx')],
            },
        ),
    ]
